/* User Action Types */
export const USERNAME_ENTERED = "USERNAME_ENTERED";
export const PASSWORD_ENTERED = "PASSWORD_ENTERED";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";

/* Feed Action Types */
export const CREATE_FEED_SUCCESS = "CREATE_FEED";
export const DELETE_FEED_SUCCESS = "DELETE_FEED";
export const GET_FEED_LIST = "GET_FEED_LIST";
export const GET_FEED_LIST_PENDING = "GET_FEED_LIST_PENDING";
export const GET_FEED_LIST_FULFILLED = "GET_FEED_LIST_FULFILLED";
export const FEED_ACTION_FAILED = "FEED_ACTION_FAILED";

/* Message Board Types */
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const POST_MESSAGE = "POST_MESSAGE";

/* Message Action Types */
export const RESOLVE_MESSAGE_ACTION_SUCCESS = "RESOLVE_MESSAGE_ACTION_SUCCESS";
export const RESOLVE_MESSAGE_ACTION_FAILED = "RESOLVE_MESSAGE_ACTION_FAILED";
